openapi: 3.0.0
info:
  title: Todo App API
  description: API used as sample during the Blog Posts series talking about API Design.
  version: "1.0"
  contact:
    email: 'nicolas.tcs@hotmail.com'
    name: 'Nicolas Takashi'
    url: 'https://nicolastakashi.medium.com'
  x-logo:
    url: "https://img.icons8.com/nolan/452/todo-list.png"
    backgroundColor: "#FFFFFF"
    altText: "Petstore logo"
  license:
    name: MIT
    url: https://raw.githubusercontent.com/nicolastakashi/todoapp-openapidocuments/master/LICENSE
servers:
  - url: http://127.0.0.1:4010
    description: Mock Server
tags:
  - name: Tasks
paths:
  '/tasks':
    $ref: './components/paths/tasks/task.yaml'
  '/tasks/{id}':
    $ref: './components/paths/tasks/task-by-id.yaml'
components:
  schemas:
    Task:
      $ref: 'components/schemas/task.yaml#/components/schemas/Task'
    PagedTask:
      $ref: 'components/schemas/pagedTask.yaml#/components/schemas/PagedTask'
    ProblemDetails:
      $ref: 'components/schemas/problemDetails.yaml#/components/schemas/ProblemDetails'