# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Yarn CLI
      uses: CultureHQ/actions-yarn@v1.0.1

    # Install project dependencies
    - name: Install dependencies
      run: yarn

    # Linting OpenAPI documents
    - name: Lint documents
      run: yarn lint

    - name: install swashbuckle CLI
      run: dotnet tool install Swashbuckle.AspNetCore.Cli --global

    - name: build api
      run: dotnet build ./api/TodoApp.Api/TodoApp.Api.csproj --configuration Release

    - name: extract api contract
      run: swagger tofile --yaml --output ./bin/swagger.yaml ./api/TodoApp.Api/bin/Release/netcoreapp3.1/TodoApp.Api.dll v1

    - name: contract test
      run: yarn contract-test
